# for unix
run-dist:
	./build/install/app/bin/app

build:
	./gradlew clean build

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

# for windows
run-dist-win:
	.\build\install\app\bin\app

build-win:
	.\gradlew clean build

test-win:
	.\gradlew test

# PHONY
.PHONY: build